# Generated by Django 5.2.4 on 2025-08-01 10:30

import django.db.models.deletion
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('department', models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Operations', 'Operations'), ('Support', 'Support'), ('Training', 'Training'), ('Development', 'Development'), ('Design', 'Design')], default='IT', max_length=50, verbose_name='Department')),
                ('image', models.ImageField(blank=True, upload_to=user.models.save_subject_image, verbose_name='Subject Image')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('display_on_frontend', models.BooleanField(default=True, verbose_name='Display on Frontend')),
            ],
            options={
                'verbose_name_plural': '2. Subjects',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Operations', 'Operations'), ('Support', 'Support'), ('Training', 'Training'), ('Development', 'Development'), ('Design', 'Design')], default='IT', max_length=50, verbose_name='Department')),
                ('name', models.CharField(max_length=250)),
                ('position', models.PositiveSmallIntegerField(verbose_name='Chapter no.')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('tutorial_video', models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Videos')),
                ('quiz', models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Quiz')),
                ('content', models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Learning Aids')),
                ('editor', models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Editor')),
                ('display_on_frontend', models.BooleanField(default=True, verbose_name='Display on Frontend')),
                ('mark_as_completed', models.BooleanField(default=False, verbose_name='Mark as completed')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='user.subject')),
            ],
            options={
                'verbose_name_plural': '3. Lessons',
                'ordering': ['position'],
            },
        ),
    ]
