# Generated by Django 5.2.4 on 2025-08-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_subject_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Operations', 'Operations'), ('Support', 'Support'), ('Training', 'Training'), ('Development', 'Development'), ('Design', 'Design')], default='IT', max_length=100),
        ),
        migrations.AddField(
            model_name='query',
            name='raised_by_role',
            field=models.CharField(choices=[('trainee', 'Trainee'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
