# Generated by Django 5.2.4 on 2025-08-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_query_department_query_raised_by_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginactivity',
            name='content_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userloginactivity',
            name='content_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
