# Generated by Django 5.2.4 on 2025-08-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userloginactivity_content_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userloginactivity',
            options={'verbose_name': 'User Login Activity', 'verbose_name_plural': 'User Login Activities'},
        ),
        migrations.RenameField(
            model_name='userloginactivity',
            old_name='ip_address',
            new_name='login_IP',
        ),
        migrations.RemoveField(
            model_name='userloginactivity',
            name='content_end_time',
        ),
        migrations.RemoveField(
            model_name='userloginactivity',
            name='content_start_time',
        ),
        migrations.RemoveField(
            model_name='userloginactivity',
            name='content_viewed',
        ),
        migrations.RemoveField(
            model_name='userloginactivity',
            name='device_info',
        ),
        migrations.RemoveField(
            model_name='userloginactivity',
            name='user',
        ),
        migrations.AddField(
            model_name='userloginactivity',
            name='login_num',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='userloginactivity',
            name='login_username',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userloginactivity',
            name='status',
            field=models.CharField(blank=True, choices=[('S', 'Success'), ('F', 'Failed')], default='S', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userloginactivity',
            name='user_agent_info',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userloginactivity',
            name='login_datetime',
            field=models.DateTimeField(),
        ),
    ]
