# Generated by Django 5.2.4 on 2025-08-18 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('user', '0005_alter_userloginactivity_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentreport',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='assessmentreport',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='assessmentreport',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='assessmentreport',
            name='score',
        ),
        migrations.RemoveField(
            model_name='assessmentreport',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='assessmentreport',
            name='trainee',
        ),
        migrations.AddField(
            model_name='assessmentreport',
            name='average_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='assessmentreport',
            name='completion_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='assessmentreport',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assessmentreport',
            name='quiz',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='assessment_reports', to='quiz.quiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentreport',
            name='report_type',
            field=models.CharField(choices=[('homework', 'Homework'), ('pre-assessment', 'Pre Assessment'), ('post-assessment', 'Post Assessment'), ('daily-quiz', 'Daily Quiz'), ('weekly-quiz', 'Weekly Quiz'), ('monthly-quiz', 'Monthly Quiz'), ('final-exam', 'Final Exam')], default='assessment', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentreport',
            name='total_trainee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentreport',
            name='trainee_attempted',
            field=models.IntegerField(default=0),
        ),
    ]
