# Generated by Django 5.2.4 on 2025-08-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_assessmentreport_assessment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
