# Generated by Django 5.2.4 on 2025-08-20 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Notification', max_length=255)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('notification_type', models.CharField(choices=[('assessment', 'Assessment'), ('module', 'Module'), ('info', 'General Info')], default='info', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(related_name='notifications_received', through='user.NotificationReceipt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notificationreceipt',
            index=models.Index(fields=['user', 'is_read'], name='user_notifi_user_id_cdedc6_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationreceipt',
            index=models.Index(fields=['notification'], name='user_notifi_notific_aabf24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationreceipt',
            unique_together={('notification', 'user')},
        ),
    ]
