# Generated by Django 5.2.4 on 2025-08-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_notification_notificationreceipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentreport',
            name='audience',
            field=models.CharField(choices=[('trainee', 'Trainee'), ('employee', 'Employee')], db_index=True, default='trainee', max_length=10),
        ),
        migrations.AlterField(
            model_name='assessmentreport',
            name='report_type',
            field=models.CharField(choices=[('homework', 'Homework'), ('pre-assessment', 'Pre Assessment'), ('post-assessment', 'Post Assessment'), ('daily-quiz', 'Daily Quiz'), ('weekly-quiz', 'Weekly Quiz'), ('monthly-quiz', 'Monthly Quiz'), ('final-exam', 'Final Exam')], default='daily-quiz', max_length=20),
        ),
    ]
