# Generated by Django 5.2.4 on 2025-08-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_assessmentreport_audience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_new',
            field=models.BooleanField(default=False, help_text='Mark as new for employee dashboard visibility'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_new',
            field=models.BooleanField(default=False, help_text='Mark as new for employee dashboard visibility'),
        ),
    ]
