# Generated by Django 5.2.4 on 2025-08-24 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_lesson_is_new_subject_is_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLessonCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_completions', to='user.employeeprofile')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='user.lesson')),
            ],
            options={
                'unique_together': {('employee', 'lesson')},
            },
        ),
    ]
