# Generated by Django 5.2.4 on 2025-08-25 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_employeelessoncompletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraineeLessonCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.lesson')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_completions', to='user.traineeprofile')),
            ],
            options={
                'unique_together': {('trainee', 'lesson')},
            },
        ),
    ]
