# Generated by Django 5.2.4 on 2025-08-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_traineelessoncompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroplanner',
            name='week',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='microplanner',
            name='days',
            field=models.CharField(default='', max_length=100),
        ),
    ]
