# Generated by Django 5.2.4 on 2025-08-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_macroplanner_week_microplanner_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macroplanner',
            name='week',
            field=models.CharField(choices=[('Week 1', 'Week 1'), ('Week 2', 'Week 2'), ('Week 3', 'Week 3'), ('Week 4', 'Week 4')], default='', max_length=100),
        ),
    ]
