# Generated by Django 5.2.4 on 2025-08-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_macroplanner_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macroplanner',
            name='week',
            field=models.CharField(choices=[('week 1', 'Week 1'), ('week 2', 'Week 2'), ('week 3', 'Week 3'), ('week 4', 'Week 4')], default='', max_length=100),
        ),
    ]
