# Generated by Django 5.2.4 on 2025-09-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_macroplanner_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroplanner',
            name='mode',
            field=models.CharField(choices=[('Theoretical', 'Theoretical'), ('Practical', 'Practical')], default='Theoretical', max_length=20),
        ),
    ]
