# Generated by Django 5.2.4 on 2025-09-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_microplanner_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile.jpg', null=True, upload_to='admin_profiles/'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile.jpg', null=True, upload_to='employee_profiles/'),
        ),
        migrations.AddField(
            model_name='traineeprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile.jpg', null=True, upload_to='trainee_profiles/'),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile.jpg', null=True, upload_to='trainer_profiles/'),
        ),
    ]
