# Generated by Django 5.2.4 on 2025-09-25 05:04

import django.core.validators
import django.db.models.deletion
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_adminprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('recipient_type', models.CharField(choices=[('GROUP', 'Group'), ('INDIVIDUAL', 'Individual')], default='GROUP', max_length=12)),
                ('department', models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Operations', 'Operations'), ('Support', 'Support'), ('Training', 'Training'), ('Development', 'Development'), ('Design', 'Design')], max_length=32)),
                ('profile_type', models.CharField(blank=True, choices=[('EMPLOYEE', 'Employee'), ('TRAINEE', 'Trainee'), ('TRAINER', 'Trainer'), ('ADMIN', 'Admin')], max_length=16)),
                ('file', models.FileField(help_text='Upload PDF (max 10 MB).', upload_to='sops/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf']), user.models.validate_pdf_mimetype, user.models.validate_max_size_10mb])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sops_created', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(blank=True, related_name='sops_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
