# Generated by Django 5.2.4 on 2025-09-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_sop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sop',
            name='profile_type',
        ),
        migrations.AddField(
            model_name='sop',
            name='target_role',
            field=models.CharField(blank=True, choices=[('trainee', 'Trainee'), ('employee', 'Employee'), ('trainer', 'Trainer'), ('admin', 'Admin')], max_length=20),
        ),
    ]
