# Generated by Django 5.2.4 on 2025-09-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_sop_profile_type_sop_target_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroplanner',
            name='role',
            field=models.CharField(choices=[('trainee', 'Trainee'), ('employee', 'Employee')], db_index=True, default='trainee', max_length=10),
        ),
        migrations.AddField(
            model_name='microplanner',
            name='role',
            field=models.CharField(choices=[('trainee', 'Trainee'), ('employee', 'Employee')], db_index=True, default='trainee', max_length=10),
        ),
    ]
