# Generated by Django 5.2.4 on 2025-09-25 11:49

import django.core.validators
import django.db.models.deletion
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_macroplanner_role_microplanner_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardLibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Operations', 'Operations'), ('Support', 'Support'), ('Training', 'Training'), ('Development', 'Development'), ('Design', 'Design')], max_length=32)),
                ('target_role', models.CharField(blank=True, choices=[('trainee', 'Trainee'), ('employee', 'Employee'), ('trainer', 'Trainer'), ('admin', 'Admin')], max_length=20)),
                ('file', models.FileField(help_text='Upload PDF (max 10 MB).', upload_to='library/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf']), user.models.validate_pdf_mimetype, user.models.validate_max_size_10mb])),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Standard Library Item',
                'verbose_name_plural': 'Standard Library',
                'ordering': ['-created_at'],
            },
        ),
    ]
