# Generated by Django 5.2.4 on 2025-09-30 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_standardlibraryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('percent', models.PositiveSmallIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_progress', to='user.courselesson')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='user.trainerprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['trainer', 'lesson'], name='user_traine_trainer_389959_idx'), models.Index(fields=['status'], name='user_traine_status_6ba091_idx')],
                'unique_together': {('trainer', 'lesson')},
            },
        ),
    ]
