# Generated by Django 5.2.4 on 2025-10-04 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_trainerlessonprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraineeFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication', models.PositiveSmallIntegerField(default=0)),
                ('subject_knowledge', models.PositiveSmallIntegerField(default=0)),
                ('mentorship', models.PositiveSmallIntegerField(default=0)),
                ('custom_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
