# Generated by Django 5.2.4 on 2026-01-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_concern_concerncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_pdfs',
            field=models.JSONField(blank=True, default=list, help_text='List of PDF file paths for this lesson'),
        ),
    ]
