# Generated by Django 5.2.4 on 2026-06-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_courses_department_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='assigned_departments',
            field=models.JSONField(blank=True, default=list, verbose_name='Assigned Branches'),
        ),
    ]
