# Generated by Django 5.2.4 on 2026-06-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_trainer_assigned_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
