# Generated by Django 5.2.4 on 2026-06-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_query_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='category',
            field=models.CharField(choices=[('assessment', 'Assessment'), ('training', 'Training'), ('general', 'General'), ('technical', 'Technical')], default='general', max_length=20),
        ),
    ]
