# Generated by Django 5.2.4 on 2026-02-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Operations', 'Operations'), ('Support', 'Support'), ('Training', 'Training'), ('Development', 'Development'), ('Design', 'Design'), ('AISC Steel Detailing', 'AISC Steel Detailing'), ('Tekla', 'Tekla'), ('Shop Editing', 'Shop Editing'), ('Shop Editor Training', 'Shop Editor Training')], default='IT', max_length=50),
        ),
    ]
