# Generated by Django 5.2.4 on 2026-09-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_image',
            field=models.ImageField(blank=True, help_text='optional image for this option', null=True, upload_to='quiz/answers/'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, help_text='optional diagram/image for the question', null=True, upload_to='quiz/questions/'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(help_text="option text/label (e.g. 'A' or 'Diagram 1' for image options)", max_length=500),
        ),
    ]
