# Generated by Django 5.2.4 on 2026-09-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_answer_answer_image_question_question_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(blank=True, default='', help_text='optional if a question image is uploaded', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, help_text='diagram/image for the question; can be the complete question', null=True, upload_to='quiz/questions/'),
        ),
    ]
