# Generated by Django 5.2.4 on 2026-09-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_question_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, default='', help_text='optional if an option image is uploaded', max_length=500),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_image',
            field=models.ImageField(blank=True, help_text='image for this option; can be the complete option', null=True, upload_to='quiz/answers/'),
        ),
    ]
