# Generated by Django 5.2.4 on 2026-10-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_answer_answer_alter_answer_answer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allow_custom_answer',
            field=models.BooleanField(default=True, help_text="show a 'write your own answer' option; it is correct if it matches the correct option's text"),
        ),
        migrations.AddField(
            model_name='resultanswer',
            name='custom_answer',
            field=models.TextField(blank=True, default='', help_text='answer typed by the user instead of picking an option'),
        ),
    ]
