# Generated by Django 5.2.4 on 2026-10-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_question_allow_custom_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='expected_answer',
            field=models.CharField(blank=True, default='', help_text="optional: a written answer matching this (or the correct option's text) is marked correct automatically; other written answers can be reviewed under Result answers", max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='allow_custom_answer',
            field=models.BooleanField(default=True, help_text="show a 'write your own answer' box (always shown when the question has no options)"),
        ),
    ]
